# Ruby CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-ruby/ for more details
#
version: 2
jobs:
  build:
    working_directory: /tmp/SlideHub
    parallelism: 1
    shell: /bin/bash --login

    docker:
      - image: circleci/ruby:2.5.0-node-browsers
        environment:
          CIRCLE_ARTIFACTS: /tmp/circleci-artifacts
          CIRCLE_TEST_REPORTS: /tmp/circleci-test-results
          CIRCLE_ENV: test
          OSS_DB_URL_TEST: 127.0.0.1
          OSS_DB_USERNAME_TEST: 'root'
          OSS_DB_PASSWORD_TEST: ''
          OSS_REGION: ap-northeast-1
          OSS_SECRET_KEY_BASE: dummy
          RAILS_ENV: test
      - image: circleci/mysql:5.7

    steps:
      - checkout
      - run: mkdir -p $CIRCLE_ARTIFACTS $CIRCLE_TEST_REPORTS/rspec
      - run: sudo npm install -g bower
      - run: sudo apt-get update
      - run: sudo apt-get install -y libmagic-dev
      - run: cd /tmp && wget --tries 3 -O freetds-1.1.4.tar.gz "ftp://ftp.freetds.org/pub/freetds/stable/freetds-1.1.4.tar.gz" && tar -xzvf freetds-1.1.4.tar.gz && cd freetds-1.1.4 && ./configure && make && sudo make install
      - run: curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
      - run: chmod +x ./cc-test-reporter

      - restore_cache:
          keys:
          # This branch if available
          - v1-dep-{{ .Branch }}-
          # Default branch if not
          - v1-dep-master-
          - v1-dep-

      - run: 'bundle check --path=vendor/bundle || bundle install --path=vendor/bundle --jobs=4 --retry=3 '

      - save_cache:
          key: v1-dep-{{ .Branch }}-{{ epoch }}
          paths:
          # This is a broad list of cache paths to include many possible development environments
          # You can probably delete some of these entries
          - vendor/bundle
          - ~/virtualenvs
          - ~/.m2
          - ~/.ivy2
          - ~/.bundle
          - ~/.go_workspace
          - ~/.gradle
          - ~/.cache/bower

      - run: bundle exec rake db:create db:migrate
      - run: ./cc-test-reporter before-build
      - run: bower install

      - run:
          command: bundle exec rspec --color --require spec_helper --format documentation --format RspecJunitFormatter --out $CIRCLE_TEST_REPORTS/rspec/rspec.xml --format progress spec
          environment:
            RAILS_ENV: test
            RACK_ENV: test

      - run: ./cc-test-reporter format-coverage -t simplecov $CIRCLE_ARTIFACTS/coverage/.resultset.json
      - run: ./cc-test-reporter upload-coverage

      - store_test_results:
          path: $CIRCLE_TEST_REPORTS
      - store_artifacts:
          path: $CIRCLE_ARTIFACTS
      - store_artifacts:
          path: $CIRCLE_TEST_REPORTS
